name: GitHub Actions Demo
  on:
    push:
      branches: [master]
    pull_request:
      branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: SetupJDK
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
