# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  schedule:
    - cron: '* * * * *'
  workflow_run:
    workflows: ["Build","Deploy"]
    types:
      - completed

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build IF
        if: |-
            !(github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Build')
          env:
            VCCRAN: 'Build'

      - name: Deploy IF
          if: |-
            !(github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Deploy')
            env:
            VCCRAN: 'Deploy'

      - name: Print Log
        run: |
          echo "$VCCRAN"
          echo ${{ VCCRAN }}
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          echo "event workflow_run event is:" ${{ github.event.workflow_run.event }}
          echo "event workflow_run name is:" ${{ github.event.workflow_run.name }}
          echo "event schedule name is:" ${{ github.event.schedule.name }}

  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Print Log
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_WORKFLOW"
          echo "$GITHUB_EVENT_NAME"
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          echo "event workflow_run event is:" ${{ github.event.workflow_run.event }}
          echo "event workflow_run name is:" ${{ github.event.workflow_run.name }}
          echo "event schedule name is:" ${{ github.event.schedule.name }}

      - uses: actions/checkout@v2

      - name: Set up JAVA 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with MVN
        run: mvn --batch-mode --update-snapshots verify

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: vccran/sample-github-actions
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: vccran/sample-github-actions:build

  deploy-java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JAVA 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with MVN
        run: mvn --batch-mode --update-snapshots verify

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: vccran/sample-github-actions
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: vccran/sample-github-actions:deploy